### ISSUE TITLE
Allow students to upload their CV

### ISSUE THREAD

**Issue by egnwd** [docsocsf/sponsor-portal-OLD#7]
Allow a student to upload a CV to their profile. This should not be visible to other students, but can be seen by the sponsors.

Blocked by #5

**Comment by mishrabhinav** [comment]
@egnwd can we ask for a link to the CV instead?

**Comment by martinzlocha** [comment]
I think that's a very good idea. It will allow students to easily update the CV without having to change the link on the portal.

**Comment by mishrabhinav** [comment]
It not necessarily saves them the trouble to update the link. It depends on service they use to host the CV.

**Comment by martinzlocha** [comment]
True, I use Dropbox thats why I thought its nice. But anyway I guess its up @egnwd.

**Comment by levex** [comment]
If you allow them to use a link, then I think (1) that needs to be checked continuously for continued-access; or (2) has to be downloaded to the sponsor-portal and served from there.

If you choose (1), then that is an interesting to problem on its own to scrap the links in some intervals to ensure continued access and send an email to the student if it goes offline. An interesting issue is how do you verify that it is indeed a CV (I'm 99% sure there are people who'd abuse the system and that puts DoCSoc in a bad position, so I'd rather avoid) once it changes.

If you choose (2), then all the problems are solved, albeit people may need to do extra labor.

Just my 2¢, thanks.

**Comment by egnwd** [comment]
I don't think this should be instead, perhaps in the future adding it as well is an option, but not everyone hosts their CV somewhere. @mishrabhinav what were your main reasons for wanting this? The things I can think of are hosting, we are obviously going to have to host them, but if we end up scraping links we will need to do that anyway
