### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by jamesprinc3** [docsocsf/sponsor-portal-OLD#8]
## Detailed Description
CircleCI is set up on the MaD repo: https://github.com/docsocsf/mad. I see no reason not to use the same here

## Context
Will allow us to confirm that a merging a given pull request keeps our code passing tests.

## Possible Implementation
https://circleci.com/docs/2.0/ has heaps of information.

**Comment by plietar** [comment]
Done using travis (#26).
